next_week_focus:
  - Focus on reducing SLA violations through proactive monitoring
  - Account Audit Projects which we have received (Infomatics)
  - Focus on Account proper mapping and ticket assignment
